service: template

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  role: arn:aws:iam::392721527794:role/service-role/2018-lambda-exec-vpc

functions:
  template-function:
    handler: handler.lambdaFunction
    environment:
      host: 'host_do_banco'
      user: 'user'
      password: 'password'
      database: 'db'
      port: 1433
    events:
      - http:
          path: template/
          method: post
